### ISSUE TITLE
funkce 4 - pridava mezeru na konci radku

### ISSUE THREAD

**Issue by petrKoukal** [progresak/CodeRefactorer#2]
pokud puvodni soubor ```messages``` obsahuje radku ukoncenou ```\```, napr.:
```
roomallocation.moretravelers.desc=In order to book this trip for a group of travelers, please continue planning for 2 travelers and then \
```
po spusteni **fce 4** je ve vysledne radce pridana mezera na konec navic, tj.
```
... and then \[mezera]
```
=> to je spatny format souboru a mame problemy

WORKAROUND: 
pokud je to slozite, muzu pomoci editoru nahradit ```" \ "``` za ```" \"```

**Comment by progresak** [comment]
Vyřešeno

**Comment by petrKoukal** [comment]
test - super!!!
