### ISSUE TITLE
funkce 4 - IndexOutOfBounds Error pri vstupu uplneho souboru Messages

### ISSUE THREAD

**Issue by petrKoukal** [progresak/CodeRefactorer#3]
Resit klidne jako nizkou prioritu, pac Workaround mi zatim staci 
- pokud pro funkci 4) pouziju nas uplny soubor Messages, dostanu:
![image](https://cloud.githubusercontent.com/assets/888576/10102087/e1a506e0-639c-11e5-9786-a299144df9bf.png)

**WORKAROUND:**
uplne mi staci, kdyz smazu vsecky hodnoty, co tam jsou dnes navic (=> Messages vypada stejne jako bylo pri zadani a fce funguje) a pak si je tam opet prilepim. 

Rad bych ale vedel, co tomu skriptu vadi (jestli je to treba jen nejaky String, radka, specialni znak, ... navic, nebo zda to ma opravdu problemy s velkym mnozstvim klicu)

Nahral jsem uplny soubor ```messages-full`` pro predstavu, nove hodnoty zacinaji **na radce 876**
https://github.com/progresak/CodeRefactorer/blob/master/messages-full

**Comment by progresak** [comment]
Chyba byla tím, že některé hodnoty měli v sobě opět '=' .. které to celé rozbilo :)
