### ISSUE TITLE
funkce 2 - vubec nefunguje

### ISSUE THREAD

**Issue by petrKoukal** [progresak/CodeRefactorer#4]
kdyz spustim fci 2, dostanu nasledujici: 

![image](https://cloud.githubusercontent.com/assets/888576/10118854/0052a4e8-6484-11e5-86d8-b5610a573d12.png)

uplne prvni verze souboru ```refactoring.jar``` pri zadani stejnych hodnot funguje spravne. Zkousel jsem i ```sudo```

Myslim ze tam je nekde prehozena radka. Zapisuje to do souboru, ktery jeste nebyl vytvoren.

**Comment by petrKoukal** [comment]
Anebo tam muze byt "s" navic - slozka ```log``` vs. ```logs```

**Comment by progresak** [comment]
Fixed, zapisoval jsem do slozky, ktera neexistovala.
