### ISSUE TITLE
funkce 2 - vklada prazdnou radku na konec otevreneho souboru

### ISSUE THREAD

**Issue by petrKoukal** [progresak/CodeRefactorer#5]
po spusteni fce 2 se ve vsech souborech, ktery skript otevira (jak ```.js```, tak ```.html```), vlozi prazdna radka na konci souboru. Na funkci algoritmu to nema vliv, ale Git pak reportuje zmeny ve vsech souborech a zbytecne nam micha s historii zmen.

Pokud by to slo, prosil bych, aby se tam ta radka nezapisovala. Lepe by se mi i kontroloval vystup funkce.

**Comment by progresak** [comment]
Fixed :)

**Comment by petrKoukal** [comment]
Ted mam pocit ze to naopak maze posledni prazdnou radku z konci souboru ;)

tady screenshot, ktery ukazuje jak Git vidi tu zmenu (nalevo orig, napravo lokalni zmeny): 
![image](https://cloud.githubusercontent.com/assets/888576/10139959/a3658718-6605-11e5-8350-b99be9cee25b.png)

**Comment by progresak** [comment]
Popravdě java pěkně blbě detekuje jestli je poslední řádek prázdný (pokud je, tak ho vůbec nenačte). Je to velký problém když to bude soubory "trimovat" od konce? :)

**Comment by petrKoukal** [comment]
v poho, pokud je to velky problem, tak to holt zkousnu. Proto jsem to znovu ani neoteviral.

**Comment by petrKoukal** [comment]
dostatecne reseni: 
1) zavolat fci s prazdym souborem `keyMap` -> ze vsech souboru se odstrani posledni prazdne radky
2) commit
3) znovu spustit fci s opravdovym souborem `keyMap` -> funguje dle predpokladu
