### ISSUE TITLE
Nesparovane klice

### ISSUE THREAD

**Issue by petrKoukal** [progresak/CodeRefactorer#6]
nasel jsem nasledujici klic, ktery se jeste chova podivne: 

```
// keyMap
booking.action.continueToSummary=action.continueToSummary
```

novy klic je spravne vyhledan a nahrazen v messages( fce 1), ale ne v ```.html``` -> soubor ```bookingTravelerDetails.scala.html:348```: 

```
<span class='text'>@Messages("booking.action.continueToSummary")</span> <span class="glyphicon glyphicon-chevron-right"></span>
```

**Comment by progresak** [comment]
špatně napsaná podmínka, již by se nemělo stávat.(nový klíč byl součástí starého)
