### ISSUE TITLE
funkce 1 - chybici klice

### ISSUE THREAD

**Issue by petrKoukal** [progresak/CodeRefactorer#7]
nasel jsem nasledujici klice:
```
// keyMap
flightsmodal.arrivaltime.error=text.arrivalTimeError
flightsmodal.departuretime.error=text.departuretimeError
```

tyhle klice se sice spravne prejmenuji v `.html`, ale uplne chybi v souboru `Messages`. Misto toho jsem tam nasel `title.departuretime.error`, ktery obsahuje stejny text jako `flightsmodal.departuretime.error`, ale takove mapovani nikde neni.

**Comment by progresak** [comment]
Fixed, už by se to nemělo stávat :)
